CREATE VIEW VW_CUSTOMER_SALES (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    TOTAL_ORDERS,
    TOTAL_SPENT
) AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    COUNT(S.ORDER_ID) AS TOTAL_ORDERS,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM FACT_SALES S
JOIN DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE;
