CREATE VIEW VW_EXECUTIVE_DASHBOARD (
    TOTAL_SALES,
    TOTAL_ORDERS,
    TOTAL_CUSTOMERS,
    TOTAL_PRODUCTS_SOLD,
    AVG_ORDER_VALUE,
    TOTAL_RETURNS,
    AVG_RATING
) AS
SELECT
    (SELECT SUM(TOTAL_AMOUNT) FROM FACT_SALES) AS TOTAL_SALES,
    (SELECT COUNT(DISTINCT ORDER_ID) FROM FACT_SALES) AS TOTAL_ORDERS,
    (SELECT COUNT(DISTINCT CUSTOMER_ID) FROM FACT_SALES) AS TOTAL_CUSTOMERS,
    (SELECT SUM(QUANTITY) FROM FACT_SALES) AS TOTAL_PRODUCTS_SOLD,
    (SELECT AVG(TOTAL_AMOUNT) FROM FACT_SALES) AS AVG_ORDER_VALUE,
    (SELECT COUNT(*) FROM FACT_RETURNS) AS TOTAL_RETURNS,
    (SELECT AVG(RATING) FROM FACT_REVIEWS) AS AVG_RATING;
