CREATE VIEW VW_PAYMENT_ANALYSIS (
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    TOTAL_PAYMENTS,
    TOTAL_AMOUNT
) AS
SELECT
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    COUNT(*) AS TOTAL_PAYMENTS,
    SUM(PAYMENT_AMOUNT) AS TOTAL_AMOUNT
FROM FACT_PAYMENTS
GROUP BY
    PAYMENT_METHOD,
    PAYMENT_STATUS;
