CREATE VIEW VW_PRODUCT_SALES (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    TOTAL_QUANTITY,
    TOTAL_SALES,
    AVG_PRICE
) AS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,
    AVG(S.UNIT_PRICE) AS AVG_PRICE
FROM FACT_SALES S
JOIN DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND;
