CREATE VIEW VW_RETURN_ANALYSIS (
    RETURN_REASON,
    RETURN_STATUS,
    TOTAL_RETURNS,
    TOTAL_REFUND
) AS
SELECT
    RETURN_REASON,
    RETURN_STATUS,
    COUNT(*) AS TOTAL_RETURNS,
    SUM(REFUND_AMOUNT) AS TOTAL_REFUND
FROM FACT_RETURNS
GROUP BY
    RETURN_REASON,
    RETURN_STATUS;
