CREATE VIEW VW_REVIEW_ANALYSIS (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    AVG_RATING,
    TOTAL_REVIEWS
) AS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    AVG(R.RATING) AS AVG_RATING,
    COUNT(R.REVIEW_ID) AS TOTAL_REVIEWS
FROM FACT_REVIEWS R
JOIN DIM_PRODUCT P
    ON R.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY;
