CREATE VIEW VW_SHIPMENT_ANALYSIS (
    SHIPMENT_STATUS,
    COURIER,
    TOTAL_SHIPMENTS
) AS
SELECT
    SHIPMENT_STATUS,
    COURIER,
    COUNT(*) AS TOTAL_SHIPMENTS
FROM FACT_SHIPMENTS
GROUP BY
    SHIPMENT_STATUS,
    COURIER;
