CREATE VIEW VW_SALES_ANALYSIS (
    SALES_KEY,
    ORDER_ITEM_ID,
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ORDER_DATE,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    TAX,
    TOTAL_AMOUNT,
    ORDER_TOTAL,
    ORDER_STATUS,
    PAYMENT_STATUS
) AS
SELECT *
FROM FACT_SALES;
