CREATE TABLE FACT_RETURNS (
    RETURN_ID NUMBER(38,0) PRIMARY KEY,
    ORDER_ID NUMBER(38,0),
    DELIVERY_DATE DATE,
    RETURN_DATE DATE,
    RETURN_REASON VARCHAR,
    REFUND_AMOUNT NUMBER(10,2),
    RETURN_STATUS VARCHAR
);