CREATE TABLE FACT_SHIPMENTS (
    SHIPMENT_ID NUMBER(38,0) PRIMARY KEY,
    ORDER_ID NUMBER(38,0),
    WAREHOUSE_ID NUMBER(38,0),
    TRACKING_NUMBER VARCHAR,
    COURIER VARCHAR,
    SHIPMENT_DATE DATE,
    DELIVERY_DATE DATE,
    SHIPMENT_STATUS VARCHAR,

    FOREIGN KEY (WAREHOUSE_ID)
        REFERENCES DIM_WAREHOUSE(WAREHOUSE_ID)
);