CREATE TABLE FACT_REVIEWS (
    REVIEW_ID NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_ID NUMBER(38,0),
    PRODUCT_ID NUMBER(38,0),
    RATING NUMBER(3,1),
    REVIEW_DATE DATE,
    REVIEW_TEXT VARCHAR,

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID)
);