CREATE TABLE FACT_SALES (
    ORDER_ITEM_ID NUMBER(38,0) PRIMARY KEY,
    ORDER_ID NUMBER(38,0),
    CUSTOMER_ID NUMBER(38,0),
    PRODUCT_ID NUMBER(38,0),
    ORDER_DATE DATE,
    QUANTITY NUMBER(38,0),
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    TAX NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),
    ORDER_TOTAL NUMBER(10,2),
    ORDER_STATUS VARCHAR,
    PAYMENT_STATUS VARCHAR,

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID)
);