CREATE TABLE FACT_PAYMENTS (
    PAYMENT_ID NUMBER(38,0) PRIMARY KEY,
    ORDER_ID NUMBER(38,0),
    TRANSACTION_ID VARCHAR,
    PAYMENT_METHOD VARCHAR,
    PAYMENT_AMOUNT NUMBER(10,2),
    PAYMENT_DATE DATE,
    PAYMENT_STATUS VARCHAR
);