

USE DATABASE REATILPULSE_DW;
USE SCHEMA REATILPULSE_SCHEMA;

-- 1. RECORD COUNT VALIDATION


SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER

UNION ALL
SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL
SELECT 'DIM_SELLER', COUNT(*)
FROM DIM_SELLER

UNION ALL
SELECT 'DIM_WAREHOUSE', COUNT(*)
FROM DIM_WAREHOUSE

UNION ALL
SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL
SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES

UNION ALL
SELECT 'FACT_PAYMENTS', COUNT(*)
FROM FACT_PAYMENTS

UNION ALL
SELECT 'FACT_SHIPMENTS', COUNT(*)
FROM FACT_SHIPMENTS

UNION ALL
SELECT 'FACT_RETURNS', COUNT(*)
FROM FACT_RETURNS

UNION ALL
SELECT 'FACT_REVIEWS', COUNT(*)
FROM FACT_REVIEWS;



-- 2. DUPLICATE ID VALIDATION


SELECT CUSTOMER_ID, COUNT(*) AS DUPLICATE_COUNT
FROM DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT PRODUCT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM DIM_PRODUCT
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 1;

SELECT SELLER_ID, COUNT(*) AS DUPLICATE_COUNT
FROM DIM_SELLER
GROUP BY SELLER_ID
HAVING COUNT(*) > 1;

SELECT WAREHOUSE_ID, COUNT(*) AS DUPLICATE_COUNT
FROM DIM_WAREHOUSE
GROUP BY WAREHOUSE_ID
HAVING COUNT(*) > 1;

SELECT DATE_KEY, COUNT(*) AS DUPLICATE_COUNT
FROM DIM_DATE
GROUP BY DATE_KEY
HAVING COUNT(*) > 1;

SELECT ORDER_ITEM_ID, COUNT(*) AS DUPLICATE_COUNT
FROM FACT_SALES
GROUP BY ORDER_ITEM_ID
HAVING COUNT(*) > 1;

SELECT PAYMENT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM FACT_PAYMENTS
GROUP BY PAYMENT_ID
HAVING COUNT(*) > 1;

SELECT SHIPMENT_ID, COUNT(*) AS DUPLICATE_COUNT
FROM FACT_SHIPMENTS
GROUP BY SHIPMENT_ID
HAVING COUNT(*) > 1;

SELECT RETURN_ID, COUNT(*) AS DUPLICATE_COUNT
FROM FACT_RETURNS
GROUP BY RETURN_ID
HAVING COUNT(*) > 1;

SELECT REVIEW_ID, COUNT(*) AS DUPLICATE_COUNT
FROM FACT_REVIEWS
GROUP BY REVIEW_ID
HAVING COUNT(*) > 1;



-- 3. NULL ID VALIDATION


SELECT COUNT(*) AS NULL_CUSTOMER_IDS
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID IS NULL;

SELECT COUNT(*) AS NULL_PRODUCT_IDS
FROM DIM_PRODUCT
WHERE PRODUCT_ID IS NULL;

SELECT COUNT(*) AS NULL_SELLER_IDS
FROM DIM_SELLER
WHERE SELLER_ID IS NULL;

SELECT COUNT(*) AS NULL_WAREHOUSE_IDS
FROM DIM_WAREHOUSE
WHERE WAREHOUSE_ID IS NULL;

SELECT COUNT(*) AS NULL_DATE_KEYS
FROM DIM_DATE
WHERE DATE_KEY IS NULL;

SELECT COUNT(*) AS NULL_ORDER_ITEM_IDS
FROM FACT_SALES
WHERE ORDER_ITEM_ID IS NULL;

SELECT COUNT(*) AS NULL_PAYMENT_IDS
FROM FACT_PAYMENTS
WHERE PAYMENT_ID IS NULL;

SELECT COUNT(*) AS NULL_SHIPMENT_IDS
FROM FACT_SHIPMENTS
WHERE SHIPMENT_ID IS NULL;

SELECT COUNT(*) AS NULL_RETURN_IDS
FROM FACT_RETURNS
WHERE RETURN_ID IS NULL;

SELECT COUNT(*) AS NULL_REVIEW_IDS
FROM FACT_REVIEWS
WHERE REVIEW_ID IS NULL;


-- 4. FOREIGN KEY / RELATIONSHIP VALIDATION


-- FACT_SALES -> DIM_CUSTOMER

SELECT COUNT(*) AS INVALID_SALES_CUSTOMERS
FROM FACT_SALES S
LEFT JOIN DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


-- FACT_SALES -> DIM_PRODUCT

SELECT COUNT(*) AS INVALID_SALES_PRODUCTS
FROM FACT_SALES S
LEFT JOIN DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;


-- DIM_PRODUCT -> DIM_SELLER

SELECT COUNT(*) AS INVALID_PRODUCT_SELLERS
FROM DIM_PRODUCT P
LEFT JOIN DIM_SELLER S
    ON P.SELLER_ID = S.SELLER_ID
WHERE S.SELLER_ID IS NULL;


-- FACT_SHIPMENTS -> DIM_WAREHOUSE

SELECT COUNT(*) AS INVALID_SHIPMENT_WAREHOUSES
FROM FACT_SHIPMENTS S
LEFT JOIN DIM_WAREHOUSE W
    ON S.WAREHOUSE_ID = W.WAREHOUSE_ID
WHERE W.WAREHOUSE_ID IS NULL;


-- FACT_REVIEWS -> DIM_CUSTOMER

SELECT COUNT(*) AS INVALID_REVIEW_CUSTOMERS
FROM FACT_REVIEWS R
LEFT JOIN DIM_CUSTOMER C
    ON R.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


-- FACT_REVIEWS -> DIM_PRODUCT

SELECT COUNT(*) AS INVALID_REVIEW_PRODUCTS
FROM FACT_REVIEWS R
LEFT JOIN DIM_PRODUCT P
    ON R.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;



-- 5. FACT SALES BUSINESS VALIDATION


SELECT COUNT(*) AS INVALID_QUANTITY
FROM FACT_SALES
WHERE QUANTITY <= 0;

SELECT COUNT(*) AS INVALID_UNIT_PRICE
FROM FACT_SALES
WHERE UNIT_PRICE < 0;

SELECT COUNT(*) AS INVALID_DISCOUNT
FROM FACT_SALES
WHERE DISCOUNT < 0;

SELECT COUNT(*) AS INVALID_TAX
FROM FACT_SALES
WHERE TAX < 0;

SELECT COUNT(*) AS INVALID_TOTAL_AMOUNT
FROM FACT_SALES
WHERE TOTAL_AMOUNT < 0;

SELECT COUNT(*) AS INVALID_ORDER_TOTAL
FROM FACT_SALES
WHERE ORDER_TOTAL < 0;


-- 6. PAYMENT VALIDATION


SELECT COUNT(*) AS INVALID_PAYMENT_AMOUNT
FROM FACT_PAYMENTS
WHERE PAYMENT_AMOUNT < 0;

SELECT PAYMENT_METHOD, COUNT(*) AS TOTAL_PAYMENTS
FROM FACT_PAYMENTS
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_PAYMENTS DESC;

SELECT PAYMENT_STATUS, COUNT(*) AS TOTAL_PAYMENTS
FROM FACT_PAYMENTS
GROUP BY PAYMENT_STATUS
ORDER BY TOTAL_PAYMENTS DESC;



-- 7. SHIPMENT VALIDATION


SELECT COUNT(*) AS INVALID_DELIVERY_DATES
FROM FACT_SHIPMENTS
WHERE DELIVERY_DATE < SHIPMENT_DATE;

SELECT SHIPMENT_STATUS, COUNT(*) AS TOTAL_SHIPMENTS
FROM FACT_SHIPMENTS
GROUP BY SHIPMENT_STATUS
ORDER BY TOTAL_SHIPMENTS DESC;

SELECT COURIER, COUNT(*) AS TOTAL_SHIPMENTS
FROM FACT_SHIPMENTS
GROUP BY COURIER
ORDER BY TOTAL_SHIPMENTS DESC;


-- 8. RETURN VALIDATION


SELECT COUNT(*) AS INVALID_REFUND_AMOUNT
FROM FACT_RETURNS
WHERE REFUND_AMOUNT < 0;

SELECT COUNT(*) AS INVALID_RETURN_DATE
FROM FACT_RETURNS
WHERE RETURN_DATE < DELIVERY_DATE;

SELECT RETURN_STATUS, COUNT(*) AS TOTAL_RETURNS
FROM FACT_RETURNS
GROUP BY RETURN_STATUS
ORDER BY TOTAL_RETURNS DESC;

SELECT RETURN_REASON, COUNT(*) AS TOTAL_RETURNS
FROM FACT_RETURNS
GROUP BY RETURN_REASON
ORDER BY TOTAL_RETURNS DESC;


-- 9. REVIEW VALIDATION


SELECT COUNT(*) AS INVALID_RATINGS
FROM FACT_REVIEWS
WHERE RATING < 1
   OR RATING > 5;

SELECT RATING, COUNT(*) AS TOTAL_REVIEWS
FROM FACT_REVIEWS
GROUP BY RATING
ORDER BY RATING;



-- 10. DIMENSION BUSINESS VALIDATION


SELECT COUNT(*) AS INVALID_PRODUCT_PRICE
FROM DIM_PRODUCT
WHERE PRICE < 0;

SELECT COUNT(*) AS INVALID_COST_PRICE
FROM DIM_PRODUCT
WHERE COST_PRICE < 0;

SELECT COUNT(*) AS INVALID_STOCK
FROM DIM_PRODUCT
WHERE STOCK < 0;

SELECT COUNT(*) AS INVALID_WAREHOUSE_CAPACITY
FROM DIM_WAREHOUSE
WHERE CAPACITY < 0;

SELECT COUNT(*) AS INVALID_SELLER_RATING
FROM DIM_SELLER
WHERE RATING < 0;


