CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    GENDER VARCHAR,
    DATE_OF_BIRTH DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    POSTAL_CODE VARCHAR,
    REGISTRATION_DATE DATE,
    CUSTOMER_STATUS VARCHAR
);