CREATE TABLE DIM_SELLER (
    SELLER_ID NUMBER(38,0) PRIMARY KEY,
    SELLER_NAME VARCHAR,
    CONTACT_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    GST_NUMBER VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    POSTAL_CODE VARCHAR,
    RATING FLOAT,
    REGISTRATION_DATE DATE,
    SELLER_STATUS VARCHAR
);