CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER(38,0) PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    BRAND VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(38,0),
    COST_PRICE NUMBER(38,0),
    STOCK NUMBER(38,0),
    WEIGHT NUMBER(38,0),
    LAUNCH_DATE DATE,
    SELLER_ID NUMBER(38,0),
    PRODUCT_STATUS VARCHAR,

    FOREIGN KEY (SELLER_ID)
        REFERENCES DIM_SELLER(SELLER_ID)
);