CREATE TABLE DIM_DATE (
    DATE_KEY NUMBER(38,0) PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER(38,0),
    QUARTER NUMBER(38,0),
    MONTH NUMBER(38,0),
    MONTH_NAME VARCHAR,
    WEEK NUMBER(38,0),
    DAY NUMBER(38,0),
    DAY_NAME VARCHAR
);