CREATE TABLE DIM_WAREHOUSE (
    WAREHOUSE_ID NUMBER(38,0) PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    POSTAL_CODE VARCHAR,
    CAPACITY NUMBER(38,0),
    MANAGER_NAME VARCHAR,
    CONTACT_NUMBER VARCHAR,
    WAREHOUSE_STATUS VARCHAR
);